development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stockhubbd_development
  pool: 5
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stockhubbd_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stockhubbd_development
  pool: 5
  username: root
  password: root